FROM python:latest

WORKDIR "/usr/src/django_app"

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirments.txt .
RUN pip install -r requirments.txt

# COPY ./investment_company .