# Generated by Django 5.0.1 on 2024-01-18 19:10

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Короткий символ акції корпорації (напр.: TSLA для Tesla)', max_length=10, unique=True)),
                ('company_name', models.CharField(help_text='Повна назва компанії', max_length=500)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Поточна ціна акції', max_digits=16)),
                ('volume', models.IntegerField(help_text='Загальна кількість акцій, які були обмінені для даної акції за день')),
                ('net_change', models.DecimalField(blank=True, decimal_places=2, help_text='Різниця між поточною ціною та ціною закриття попереднього дня', max_digits=16, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='Відсоткова зміна ціни акцій або цінного паперу в порівнянні із ціною закриття попереднього дня', max_digits=5, null=True)),
                ('market_capitalization', models.DecimalField(decimal_places=2, help_text='Загальна ринкова вартість всіх випущених акцій компанії', max_digits=23)),
                ('country', models.CharField(help_text='Країна, в якій знаходиться або має своє головне підрозділ компанія', max_length=100)),
                ('ipo', models.PositiveIntegerField(help_text='Рік, коли компанія вийшла на публічний ринок, випустивши свою першу публічну пропозицію акцій. Формат: YYYY.', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2024)])),
                ('sector', models.CharField(help_text='Широка категорія, яка класифікує компанії в різні групи на основі характеру їхньої діяльності', max_length=100)),
                ('industry', models.CharField(help_text='Більш конкретна класифікація, яка подальш розділяє компанії в межах сектора відповідно до їхнього конкретного напрямку діяльності чи пропозицій продуктів/послуг', max_length=100)),
                ('last_price_change', models.DateTimeField(auto_now=True, help_text='Останній раз, коли була перевіренна ціна на одну акцію')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ім'я клієнта", max_length=50)),
                ('surname', models.CharField(blank=True, help_text='Прізвище клієнта', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Електронна пошта клієнта', max_length=254, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Телефонний номер клієнта', max_length=128, region=None, unique=True)),
                ('account', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(help_text='Назва інвестиційного портфелю', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Дата та час, коли був створений портфель. Додається автоматично')),
                ('client', models.ForeignKey(help_text='Якому клієнту належить даний інвестиційний портфель', on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ціна акції', max_digits=16)),
                ('save_date', models.DateTimeField(help_text='Дата, коли данна ціна була в акції')),
                ('stock', models.ForeignKey(help_text='Для якої акції зберігаються ціни', on_delete=django.db.models.deletion.CASCADE, to='mainapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ammount', models.IntegerField(help_text='Кількість акцій, з якими проводиться транзакція')),
                ('price', models.DecimalField(decimal_places=7, help_text='Вартість транзакції', max_digits=23)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Купівля'), ('SELL', 'Продаж')], default='BUY', help_text='Тип транзакції', max_length=4)),
                ('deal_date', models.DateTimeField(auto_now_add=True, help_text='Дата та час ухвалення транзакції')),
                ('portfolio', models.ForeignKey(help_text='Портфель, з яким проводиться транзакція', on_delete=django.db.models.deletion.CASCADE, to='mainapp.portfolio')),
                ('stock', models.ForeignKey(help_text='З якою акцією проводиться транзакція', on_delete=django.db.models.deletion.CASCADE, to='mainapp.stock')),
            ],
        ),
    ]
