# Generated by Django 5.0.1 on 2024-01-18 20:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Електронна пошта клієнта', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Телефонний номер клієнта', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(help_text='Прізвище клієнта', max_length=50, null=True),
        ),
    ]
