# Generated by Django 5.0.1 on 2024-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_client_email_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Електронна пошта клієнта', max_length=254, unique=True),
        ),
    ]
